// Registro de usuario
export const USUARIO_REGISTRO_EXITO = 'USUARIO_REGISTRO_EXITO'; 
export const USUARIO_REGISTRO_ERROR = 'USUARIO_REGISTRO_ERROR'; 
export const USUARIO_REGISTRO_RESET = 'USUARIO_REGISTRO_RESET';

// Autenticación de usuarios
export const USUARIO_LOGIN_EXITO = 'USUARIO_LOGIN_EXITO';
export const USUARIO_LOGIN_ERROR = 'USUARIO_LOGIN_ERROR';

// Ausuario autenticado
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';
