// Registro de usuario
export const USUARIO_REGISTRO_INICIO = 'USUARIO_REGISTRO_INICIO';
export const USUARIO_REGISTRO_EXITOSO = 'USUARIO_REGISTRO_EXITOSO'; 
export const USUARIO_REGISTRO_ERROR = 'USUARIO_REGISTRO_ERROR'; 
export const USUARIO_REGISTRO_RESET = 'USUARIO_REGISTRO_RESET';

export const USUARIO_AUTENTICADO_INICIO = 'USUARIO_AUTENTICADO_INICIO';