// Registro de usuario
export const USUARIO_REGISTRO_EXITO = 'USUARIO_REGISTRO_EXITO'; 
export const USUARIO_REGISTRO_ERROR = 'USUARIO_REGISTRO_ERROR'; 
export const USUARIO_REGISTRO_RESET = 'USUARIO_REGISTRO_RESET';

// Autenticación de usuarios
export const USUARIO_LOGIN_EXITO = 'USUARIO_LOGIN_EXITO';
export const USUARIO_LOGIN_ERROR = 'USUARIO_LOGIN_ERROR';

// Ausuario autenticado
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';


// Subida de archivos
export const SUBIR_ARCHIVO_INICIO = 'SUBIR_ARCHIVO_INICIO';
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO';
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR';

// Crear enlaces
export const CREAR_ENLACE_EXITO = 'CREAR_ENLACE_EXITO';
export const CREAR_ENLACE_ERROR = 'CREAR_ENLACE_ERROR'; 

// Mostrar alerta
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'; 
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
